package com.wifi.utils;

public class Constants {
    public static final String EVENT_WIFI_P2P_STATE_ENABLED = "EVENT_WIFI_P2P_STATE_ENABLED";
    public static final String EVENT_WIFI_P2P_STATE_DISABLED = "EVENT_WIFI_P2P_STATE_ENABLED";
    public static final String EVENT_WIFI_CONNECTION_SUCCESS = "EVENT_WIFI_CONNECTION_SUCCESS";
    public static final String EVENT_WIFI_CONNECTION_FAILURE = "EVENT_WIFI_CONNECTION_FAILURE";
    public static final String EVENT_WIFI_P2P_CONNECTION_CHANGED_ACTION = "EVENT_WIFI_P2P_CONNECTION_CHANGED_ACTION";
    public static final String EVENT_WIFI_ACTION_PEER_LIST = "EVENT_WIFI_ACTION_PEER_LIST";
    public static final String EVENT_WIFI_DISCOVERY_STARTED = "EVENT_WIFI_DISCOVERY_STARTED";
    public static final String EVENT_WIFI_DISCOVERY_STOPPED = "EVENT_WIFI_DISCOVERY_STOPPED";
    public static final String EVENT_WIFI_PEERS_AVAILABLE = "EVENT_WIFI_PEERS_AVAILABLE";
    public static final String EVENT_WIFI_CONNECTION_OWNER = "EVENT_WIFI_CONNECTION_OWNER";
    public static final String EVENT_WIFI_CONNECTION_CLIENT = "EVENT_WIFI_CONNECTION_CLIENT";
    public static final String EVENT_WIFI_MESSAGE_RECEIVED = "EVENT_WIFI_MESSAGE_RECEIVED";
}
